version: "3.8"

services:
    app:
        build:
            context: ./
            dockerfile: dev.Dockerfile
        image: asanbar-ag-alpine
        container_name: ag-panel
        restart: unless-stopped
        working_dir: /var/www/html
        tty: true
        ports:
            - "8080:8080"
        volumes:
            - ./:/var/www/html
        extra_hosts:
          - "host.docker.internal:host-gateway"
        networks:
            - asanbar-ag
    redis:
        image: redis:alpine
        container_name: ag-redis
        hostname: redis
        ports:
            - '6479:6379'
        networks:
            - asanbar-ag
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

networks:
    asanbar-ag:

volumes:
    selenium:

